trigger:
- main   # Runs pipeline on commits to main branch

pool:
  vmImage: 'ubuntu-latest'   # Build agent OS

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'    # Node.js version
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build project'

- script: npm test
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
